[all:vars]
ansible_user=ec2-user
ansible_ssh_private_key_file=~/Downloads/eap.pem
postgres_username=user1
postgres_password=pass$W0rd!
postgres_db=wildfly

# Placeholder Group
[demo]

# jboss Group
[jboss]

# pgsql group
[pgsql]

[demo:children]
jboss
