---
collections:
  - name: middleware_automation.wildfly
    version: "==1.0.5"
  - name: community.aws
  - name: amazon.aws
    version: "==3.3.1"
  - name: community.general
  - name: middleware_automation.jcliff
    version: ">=0.0.23"